// AUTO-GENERATED by scripts/fetch-gifs.mjs — local GIF library
// (files in public/gifs/, mirrored to upload/veil-gifs/). Do not hand-edit;
// re-run the script to refresh.

export type GifEntry = { file: string; tags: string[] }

export const GIF_LIBRARY: GifEntry[] = [
  {
    "file": "happy-X0oHiuYylz2Dn0nRMU.gif",
    "tags": [
      "happy",
      "glad",
      "smile",
      "yay"
    ]
  },
  {
    "file": "happy-3rgXBxX4myufzT6N2w.gif",
    "tags": [
      "happy",
      "glad",
      "smile",
      "yay"
    ]
  },
  {
    "file": "happy-Ujb2pmjn2v98Np0iPd.gif",
    "tags": [
      "happy",
      "glad",
      "smile",
      "yay"
    ]
  },
  {
    "file": "happy-A74hpgJrshTyfHZGfZ.gif",
    "tags": [
      "happy",
      "glad",
      "smile",
      "yay"
    ]
  },
  {
    "file": "happy-PklKBQ4bj7XXRHByqs.gif",
    "tags": [
      "happy",
      "glad",
      "smile",
      "yay"
    ]
  },
  {
    "file": "excited-qPKdzt3x44wy4.gif",
    "tags": [
      "excited",
      "hype",
      "energetic"
    ]
  },
  {
    "file": "excited-BcfbSp4hvude8.gif",
    "tags": [
      "excited",
      "hype",
      "energetic"
    ]
  },
  {
    "file": "excited-t3sZxY5zS5B0z5zMIz.gif",
    "tags": [
      "excited",
      "hype",
      "energetic"
    ]
  },
  {
    "file": "excited-S9i8jJxTvAKVHVMvvW.gif",
    "tags": [
      "excited",
      "hype",
      "energetic"
    ]
  },
  {
    "file": "love-JLcCHfbRPDbw1yqurX.gif",
    "tags": [
      "love",
      "heart",
      "adore"
    ]
  },
  {
    "file": "love-zrxazUScjhxo4.gif",
    "tags": [
      "love",
      "heart",
      "adore"
    ]
  },
  {
    "file": "love-3ZZRxR8GokR35zZrSw.gif",
    "tags": [
      "love",
      "heart",
      "adore"
    ]
  },
  {
    "file": "love-JbuPg6kgbQnjzUAEXp.gif",
    "tags": [
      "love",
      "heart",
      "adore"
    ]
  },
  {
    "file": "love-1sSfhxzWHJ4vC.gif",
    "tags": [
      "love",
      "heart",
      "adore"
    ]
  },
  {
    "file": "sad-SrKbU4TRDgN8apkkES.gif",
    "tags": [
      "sad",
      "unhappy",
      "depressing"
    ]
  },
  {
    "file": "sad-a9xhxAxaqOfQs.gif",
    "tags": [
      "sad",
      "unhappy",
      "depressing"
    ]
  },
  {
    "file": "sad-hiKsXXrkYopMir8ZTV.gif",
    "tags": [
      "sad",
      "unhappy",
      "depressing"
    ]
  },
  {
    "file": "sad-TpsuCxwsNH8gatbpR5.gif",
    "tags": [
      "sad",
      "unhappy",
      "depressing"
    ]
  },
  {
    "file": "sad-7Dcp8fnOFp0spXxQIo.gif",
    "tags": [
      "sad",
      "unhappy",
      "depressing"
    ]
  },
  {
    "file": "cry-xULW8r5YaVehKIN0u4.gif",
    "tags": [
      "cry",
      "crying",
      "tears",
      "sob"
    ]
  },
  {
    "file": "cry-gFwNbWLX8STN1qwPuL.gif",
    "tags": [
      "cry",
      "crying",
      "tears",
      "sob"
    ]
  },
  {
    "file": "cry-rLOzJMbJMQG7SeCDdT.gif",
    "tags": [
      "cry",
      "crying",
      "tears",
      "sob"
    ]
  },
  {
    "file": "cry-wwjnfayuGNZvoklIos.gif",
    "tags": [
      "cry",
      "crying",
      "tears",
      "sob"
    ]
  },
  {
    "file": "cry-wOgWRpJVLoPfQqp4U1.gif",
    "tags": [
      "cry",
      "crying",
      "tears",
      "sob"
    ]
  },
  {
    "file": "angry-okrv1eWeKVM9W.gif",
    "tags": [
      "angry",
      "mad",
      "rage",
      "annoyed"
    ]
  },
  {
    "file": "angry-u0kxUtHbdCKs0.gif",
    "tags": [
      "angry",
      "mad",
      "rage",
      "annoyed"
    ]
  },
  {
    "file": "angry-J3T9b6JFfxFT2.gif",
    "tags": [
      "angry",
      "mad",
      "rage",
      "annoyed"
    ]
  },
  {
    "file": "angry-7RZUr7OSOAhTG.gif",
    "tags": [
      "angry",
      "mad",
      "rage",
      "annoyed"
    ]
  },
  {
    "file": "angry-M6TiHJCalbjaWzzBmv.gif",
    "tags": [
      "angry",
      "mad",
      "rage",
      "annoyed"
    ]
  },
  {
    "file": "laugh-anYBNhqT2BYcg.gif",
    "tags": [
      "laugh",
      "laughing",
      "lol",
      "haha"
    ]
  },
  {
    "file": "laugh-JwkyzicI065lbSzyhn.gif",
    "tags": [
      "laugh",
      "laughing",
      "lol",
      "haha"
    ]
  },
  {
    "file": "laugh-IhyGL914g9ShHdHVFy.gif",
    "tags": [
      "laugh",
      "laughing",
      "lol",
      "haha"
    ]
  },
  {
    "file": "laugh-l0ExayQDzrI2xOb8A.gif",
    "tags": [
      "laugh",
      "laughing",
      "lol",
      "haha"
    ]
  },
  {
    "file": "laugh-ek8qTx5yijpNQZV8Cb.gif",
    "tags": [
      "laugh",
      "laughing",
      "lol",
      "haha"
    ]
  },
  {
    "file": "funny-PfPgPP9VX3m5O05sba.gif",
    "tags": [
      "funny",
      "joke",
      "comedy"
    ]
  },
  {
    "file": "funny-EHKlIWhmO1SRneOQrU.gif",
    "tags": [
      "funny",
      "joke",
      "comedy"
    ]
  },
  {
    "file": "funny-fWPIMfo5uMsr7qnX1Y.gif",
    "tags": [
      "funny",
      "joke",
      "comedy"
    ]
  },
  {
    "file": "funny-oYIfRmGWWlpIMjJEB5.gif",
    "tags": [
      "funny",
      "joke",
      "comedy"
    ]
  },
  {
    "file": "funny-tSyz3vcCTACjUEoaUm.gif",
    "tags": [
      "funny",
      "joke",
      "comedy"
    ]
  },
  {
    "file": "wow-giVqxWGI5xQB0TumVy.gif",
    "tags": [
      "wow",
      "amazed",
      "amazing"
    ]
  },
  {
    "file": "wow-3XR0chfiSTtAI.gif",
    "tags": [
      "wow",
      "amazed",
      "amazing"
    ]
  },
  {
    "file": "wow-5VKbvrjxpVJCM.gif",
    "tags": [
      "wow",
      "amazed",
      "amazing"
    ]
  },
  {
    "file": "wow-l3ih6qeGrTfPO.gif",
    "tags": [
      "wow",
      "amazed",
      "amazing"
    ]
  },
  {
    "file": "wow-8xHodM1bkl7FylmNAv.gif",
    "tags": [
      "wow",
      "amazed",
      "amazing"
    ]
  },
  {
    "file": "shock-LJPfWhMCs9Rks.gif",
    "tags": [
      "shock",
      "shocked",
      "surprised",
      "gasp"
    ]
  },
  {
    "file": "shock-IYjcAIri8C7f8LvLor.gif",
    "tags": [
      "shock",
      "shocked",
      "surprised",
      "gasp"
    ]
  },
  {
    "file": "shock-MuTenSRsJ7TQQ.gif",
    "tags": [
      "shock",
      "shocked",
      "surprised",
      "gasp"
    ]
  },
  {
    "file": "shock-69qBJx1zOcp07mIeVN.gif",
    "tags": [
      "shock",
      "shocked",
      "surprised",
      "gasp"
    ]
  },
  {
    "file": "shock-L3QT1L99qG7M6gFRpM.gif",
    "tags": [
      "shock",
      "shocked",
      "surprised",
      "gasp"
    ]
  },
  {
    "file": "scared-0sdj5KzXWK1ZEmYWaL.gif",
    "tags": [
      "scared",
      "afraid",
      "fear",
      "scream"
    ]
  },
  {
    "file": "scared-3QFdelWhygUMrxexy1.gif",
    "tags": [
      "scared",
      "afraid",
      "fear",
      "scream"
    ]
  },
  {
    "file": "scared-4Y49dF58S3y3GUgBUp.gif",
    "tags": [
      "scared",
      "afraid",
      "fear",
      "scream"
    ]
  },
  {
    "file": "scared-XfnRxrSQRL9MaZwRWB.gif",
    "tags": [
      "scared",
      "afraid",
      "fear",
      "scream"
    ]
  },
  {
    "file": "scared-kAjn7FOMGozJhNIud9.gif",
    "tags": [
      "scared",
      "afraid",
      "fear",
      "scream"
    ]
  },
  {
    "file": "thinking-y3QOvy7xxMwKI.gif",
    "tags": [
      "thinking",
      "hmm",
      "think"
    ]
  },
  {
    "file": "thinking-SqfHFPbzxw98xwFOiE.gif",
    "tags": [
      "thinking",
      "hmm",
      "think"
    ]
  },
  {
    "file": "thinking-rieB6hYg1l15KrJJnk.gif",
    "tags": [
      "thinking",
      "hmm",
      "think"
    ]
  },
  {
    "file": "thinking-5XELueHTZd3XCaMGbw.gif",
    "tags": [
      "thinking",
      "hmm",
      "think"
    ]
  },
  {
    "file": "thinking-872o15eAXFBw66UfNl.gif",
    "tags": [
      "thinking",
      "hmm",
      "think"
    ]
  },
  {
    "file": "sleepy-h7DyKGq716JMI.gif",
    "tags": [
      "sleepy",
      "tired",
      "sleep",
      "zzz"
    ]
  },
  {
    "file": "sleepy-l1KVaj5UcbHwrBMqI.gif",
    "tags": [
      "sleepy",
      "tired",
      "sleep",
      "zzz"
    ]
  },
  {
    "file": "sleepy-OjmrBW4ZQbWjkq6RkC.gif",
    "tags": [
      "sleepy",
      "tired",
      "sleep",
      "zzz"
    ]
  },
  {
    "file": "sleepy-TSVTlZqG4NJAs.gif",
    "tags": [
      "sleepy",
      "tired",
      "sleep",
      "zzz"
    ]
  },
  {
    "file": "sleepy-I4G0jcOtIyagIT8Ory.gif",
    "tags": [
      "sleepy",
      "tired",
      "sleep",
      "zzz"
    ]
  },
  {
    "file": "bored-ZgqJGwh2tLj5C.gif",
    "tags": [
      "bored",
      "boring",
      "meh"
    ]
  },
  {
    "file": "bored-Qz3fzoG7zhRup5sfzY.gif",
    "tags": [
      "bored",
      "boring",
      "meh"
    ]
  },
  {
    "file": "bored-F3BeiZNq6VbDwyxzxF.gif",
    "tags": [
      "bored",
      "boring",
      "meh"
    ]
  },
  {
    "file": "bored-3d5O10XObbr8LW4bDY.gif",
    "tags": [
      "bored",
      "boring",
      "meh"
    ]
  },
  {
    "file": "bored-4PvmF62Tl3KLe.gif",
    "tags": [
      "bored",
      "boring",
      "meh"
    ]
  },
  {
    "file": "dance-FBzqZGthkW6KQ.gif",
    "tags": [
      "dance",
      "dancing",
      "moves"
    ]
  },
  {
    "file": "dance-NtHHkE5KTf6eCfN2sV.gif",
    "tags": [
      "dance",
      "dancing",
      "moves"
    ]
  },
  {
    "file": "dance-KphlfEEwh1d4rpQNbo.gif",
    "tags": [
      "dance",
      "dancing",
      "moves"
    ]
  },
  {
    "file": "dance-xUA7b68hKy839wiVJC.gif",
    "tags": [
      "dance",
      "dancing",
      "moves"
    ]
  },
  {
    "file": "party-xT8qAY7e9If38xkrIY.gif",
    "tags": [
      "party",
      "celebrate",
      "celebration",
      "confetti"
    ]
  },
  {
    "file": "party-blSTtZehjAZ8I.gif",
    "tags": [
      "party",
      "celebrate",
      "celebration",
      "confetti"
    ]
  },
  {
    "file": "party-BdwNMDEnil5wk.gif",
    "tags": [
      "party",
      "celebrate",
      "celebration",
      "confetti"
    ]
  },
  {
    "file": "party-149EV8wlV75ZQc.gif",
    "tags": [
      "party",
      "celebrate",
      "celebration",
      "confetti"
    ]
  },
  {
    "file": "party-1L3xsi7WHiBjO.gif",
    "tags": [
      "party",
      "celebrate",
      "celebration",
      "confetti"
    ]
  },
  {
    "file": "congrats-9uoYC7cjcU6w8.gif",
    "tags": [
      "congrats",
      "congratulations",
      "well done"
    ]
  },
  {
    "file": "congrats-bKBM7H63PIykM.gif",
    "tags": [
      "congrats",
      "congratulations",
      "well done"
    ]
  },
  {
    "file": "congrats-xT77XWum9yH7zNkFW0.gif",
    "tags": [
      "congrats",
      "congratulations",
      "well done"
    ]
  },
  {
    "file": "congrats-RIjVnmAtOD4l4c2Ert.gif",
    "tags": [
      "congrats",
      "congratulations",
      "well done"
    ]
  },
  {
    "file": "congrats-N83kKkDvpKpTv7rZKc.gif",
    "tags": [
      "congrats",
      "congratulations",
      "well done"
    ]
  },
  {
    "file": "thanks-i21tixUQEE7TEqwmYa.gif",
    "tags": [
      "thanks",
      "thank you",
      "thx"
    ]
  },
  {
    "file": "thanks-26gsjCZpPolPr3sBy.gif",
    "tags": [
      "thanks",
      "thank you",
      "thx"
    ]
  },
  {
    "file": "thanks-BYoRqTmcgzHcL9TCy1.gif",
    "tags": [
      "thanks",
      "thank you",
      "thx"
    ]
  },
  {
    "file": "thanks-Ql6WCH22Grmpi.gif",
    "tags": [
      "thanks",
      "thank you",
      "thx"
    ]
  },
  {
    "file": "thanks-M9NbzZjAcxq9jS9LZJ.gif",
    "tags": [
      "thanks",
      "thank you",
      "thx"
    ]
  },
  {
    "file": "sorry-d7fTn7iSd2ivS.gif",
    "tags": [
      "sorry",
      "apology",
      "apologize"
    ]
  },
  {
    "file": "sorry-5w3RO3Ko72PHggK8iJ.gif",
    "tags": [
      "sorry",
      "apology",
      "apologize"
    ]
  },
  {
    "file": "sorry-uVynaMv08qg7eT72R5.gif",
    "tags": [
      "sorry",
      "apology",
      "apologize"
    ]
  },
  {
    "file": "sorry-sfHtXjURRLJrViSObF.gif",
    "tags": [
      "sorry",
      "apology",
      "apologize"
    ]
  },
  {
    "file": "sorry-nVa33aZBzefpk1cikS.gif",
    "tags": [
      "sorry",
      "apology",
      "apologize"
    ]
  },
  {
    "file": "bye-Ru9sjtZ09XOEg.gif",
    "tags": [
      "bye",
      "goodbye",
      "farewell"
    ]
  },
  {
    "file": "bye-k4ta29T68xlfi.gif",
    "tags": [
      "bye",
      "goodbye",
      "farewell"
    ]
  },
  {
    "file": "bye-1jkVi22T6iUrQJUNqk.gif",
    "tags": [
      "bye",
      "goodbye",
      "farewell"
    ]
  },
  {
    "file": "bye-kaBU6pgv0OsPHz2yxy.gif",
    "tags": [
      "bye",
      "goodbye",
      "farewell"
    ]
  },
  {
    "file": "bye-COAg7vjpWW8Ja.gif",
    "tags": [
      "bye",
      "goodbye",
      "farewell"
    ]
  },
  {
    "file": "hi-ASd0Ukj0y3qMM.gif",
    "tags": [
      "hi",
      "hello",
      "hey",
      "wave"
    ]
  },
  {
    "file": "hi-dzaUX7CAG0Ihi.gif",
    "tags": [
      "hi",
      "hello",
      "hey",
      "wave"
    ]
  },
  {
    "file": "hi-3bc9YL28QWi3pYzi1p.gif",
    "tags": [
      "hi",
      "hello",
      "hey",
      "wave"
    ]
  },
  {
    "file": "hi-dw36yjtOAtuSZyxEJG.gif",
    "tags": [
      "hi",
      "hello",
      "hey",
      "wave"
    ]
  },
  {
    "file": "hi-l0FF56cexcW2JAXCJj.gif",
    "tags": [
      "hi",
      "hello",
      "hey",
      "wave"
    ]
  },
  {
    "file": "yes-RrVzUOXldFe8M.gif",
    "tags": [
      "yes",
      "yeah",
      "agree"
    ]
  },
  {
    "file": "yes-5oGIdt1xapQ76.gif",
    "tags": [
      "yes",
      "yeah",
      "agree"
    ]
  },
  {
    "file": "yes-nFjDu1LjEADh6.gif",
    "tags": [
      "yes",
      "yeah",
      "agree"
    ]
  },
  {
    "file": "yes-13ZHjidRzoi7n2.gif",
    "tags": [
      "yes",
      "yeah",
      "agree"
    ]
  },
  {
    "file": "yes-KffdTQfewxdbKTGEJY.gif",
    "tags": [
      "yes",
      "yeah",
      "agree"
    ]
  },
  {
    "file": "no-HTzo7cfJHNY8jfq5i8.gif",
    "tags": [
      "no",
      "nope",
      "nah",
      "disagree"
    ]
  },
  {
    "file": "no-CTmxnNaVPooCs.gif",
    "tags": [
      "no",
      "nope",
      "nah",
      "disagree"
    ]
  },
  {
    "file": "no-H4zeDO4ocDYqY.gif",
    "tags": [
      "no",
      "nope",
      "nah",
      "disagree"
    ]
  },
  {
    "file": "no-QAEvvHExIlN3O66Wrz.gif",
    "tags": [
      "no",
      "nope",
      "nah",
      "disagree"
    ]
  },
  {
    "file": "no-fCTsbrpWWROGqVHsZc.gif",
    "tags": [
      "no",
      "nope",
      "nah",
      "disagree"
    ]
  },
  {
    "file": "shrug-9SINEn8jWy7xzFquPG.gif",
    "tags": [
      "shrug",
      "idk",
      "whatever",
      "meh"
    ]
  },
  {
    "file": "shrug-yj5oYHjoIwv28.gif",
    "tags": [
      "shrug",
      "idk",
      "whatever",
      "meh"
    ]
  },
  {
    "file": "shrug-CiwhnNur3uNTX0t4N4.gif",
    "tags": [
      "shrug",
      "idk",
      "whatever",
      "meh"
    ]
  },
  {
    "file": "shrug-1yTcE7OlChz4qU0ehj.gif",
    "tags": [
      "shrug",
      "idk",
      "whatever",
      "meh"
    ]
  },
  {
    "file": "shrug-130d6vlmqNcqxG.gif",
    "tags": [
      "shrug",
      "idk",
      "whatever",
      "meh"
    ]
  },
  {
    "file": "facepalm-3og0INyCmHlNylks9O.gif",
    "tags": [
      "facepalm",
      "smh",
      "doh"
    ]
  },
  {
    "file": "facepalm-14aUO0Mf7dWDXW.gif",
    "tags": [
      "facepalm",
      "smh",
      "doh"
    ]
  },
  {
    "file": "facepalm-TIycDsL2ssFPouNHMs.gif",
    "tags": [
      "facepalm",
      "smh",
      "doh"
    ]
  },
  {
    "file": "facepalm-gnJgBlPgHtcnS.gif",
    "tags": [
      "facepalm",
      "smh",
      "doh"
    ]
  },
  {
    "file": "facepalm-gLrWjmW6XljZC.gif",
    "tags": [
      "facepalm",
      "smh",
      "doh"
    ]
  },
  {
    "file": "thumbs-up-kNom41M781thYYWybb.gif",
    "tags": [
      "thumbs up",
      "approve",
      "nice"
    ]
  },
  {
    "file": "thumbs-up-YDUaNBTTy1GdNSZZRe.gif",
    "tags": [
      "thumbs up",
      "approve",
      "nice"
    ]
  },
  {
    "file": "thumbs-up-h149bSNaF5bBuMTZeU.gif",
    "tags": [
      "thumbs up",
      "approve",
      "nice"
    ]
  },
  {
    "file": "thumbs-up-SShJcu4ySty1G6MX9A.gif",
    "tags": [
      "thumbs up",
      "approve",
      "nice"
    ]
  },
  {
    "file": "thumbs-up-LVIbmaUwpRJ1C.gif",
    "tags": [
      "thumbs up",
      "approve",
      "nice"
    ]
  },
  {
    "file": "clap-2xIOiAPXonois.gif",
    "tags": [
      "clap",
      "clapping",
      "applause",
      "bravo"
    ]
  },
  {
    "file": "clap-1rOVfYAmatiYgLsxmK.gif",
    "tags": [
      "clap",
      "clapping",
      "applause",
      "bravo"
    ]
  },
  {
    "file": "clap-NJZMSqRY3rG9i.gif",
    "tags": [
      "clap",
      "clapping",
      "applause",
      "bravo"
    ]
  },
  {
    "file": "clap-dOJt6XZlQw8qQ.gif",
    "tags": [
      "clap",
      "clapping",
      "applause",
      "bravo"
    ]
  },
  {
    "file": "cat-fgWkTmhl5nGpBleFmx.gif",
    "tags": [
      "cat",
      "cats",
      "kitten",
      "kitty"
    ]
  },
  {
    "file": "cat-5T3uYeKr1PE6xhfNcX.gif",
    "tags": [
      "cat",
      "cats",
      "kitten",
      "kitty"
    ]
  },
  {
    "file": "cat-KsMT02cXvy0AN7j4Md.gif",
    "tags": [
      "cat",
      "cats",
      "kitten",
      "kitty"
    ]
  },
  {
    "file": "cat-uyfgCPQeCjYMVxt2m3.gif",
    "tags": [
      "cat",
      "cats",
      "kitten",
      "kitty"
    ]
  },
  {
    "file": "dog-1ZNI35FsYGMtko7m9k.gif",
    "tags": [
      "dog",
      "dogs",
      "puppy",
      "pup"
    ]
  },
  {
    "file": "dog-pITWhbdsnRsps6871g.gif",
    "tags": [
      "dog",
      "dogs",
      "puppy",
      "pup"
    ]
  },
  {
    "file": "dog-yrXpKtPsEnENonVG6h.gif",
    "tags": [
      "dog",
      "dogs",
      "puppy",
      "pup"
    ]
  },
  {
    "file": "dog-gKHGnB1ml0moQdjhEJ.gif",
    "tags": [
      "dog",
      "dogs",
      "puppy",
      "pup"
    ]
  },
  {
    "file": "dog-mbScAGRcQdpvIYPLbF.gif",
    "tags": [
      "dog",
      "dogs",
      "puppy",
      "pup"
    ]
  },
  {
    "file": "gaming-y0NFayaBeiWEU.gif",
    "tags": [
      "gaming",
      "game",
      "gamer",
      "videogame"
    ]
  },
  {
    "file": "gaming-U6mdTd5vdmDkhdFaxE.gif",
    "tags": [
      "gaming",
      "game",
      "gamer",
      "videogame"
    ]
  },
  {
    "file": "gaming-o4FQwsg7CmI6SjE49c.gif",
    "tags": [
      "gaming",
      "game",
      "gamer",
      "videogame"
    ]
  },
  {
    "file": "gaming-5rlcTq5MAyYLhL6BsL.gif",
    "tags": [
      "gaming",
      "game",
      "gamer",
      "videogame"
    ]
  },
  {
    "file": "gaming-ywh40EUtIfrzyqVijx.gif",
    "tags": [
      "gaming",
      "game",
      "gamer",
      "videogame"
    ]
  },
  {
    "file": "win-KEVNWkmWm6dm8.gif",
    "tags": [
      "win",
      "winning",
      "victory",
      "success"
    ]
  },
  {
    "file": "win-K3RxMSrERT8iI.gif",
    "tags": [
      "win",
      "winning",
      "victory",
      "success"
    ]
  },
  {
    "file": "win-xNBcChLQt7s9a.gif",
    "tags": [
      "win",
      "winning",
      "victory",
      "success"
    ]
  },
  {
    "file": "win-x0kMYoT7J31i8.gif",
    "tags": [
      "win",
      "winning",
      "victory",
      "success"
    ]
  },
  {
    "file": "win-N7DDovVvGnPf2jWn6Q.gif",
    "tags": [
      "win",
      "winning",
      "victory",
      "success"
    ]
  },
  {
    "file": "fail-lpHJZlhEKDyUafGTRW.gif",
    "tags": [
      "fail",
      "oops",
      "faceplant"
    ]
  },
  {
    "file": "fail-ZdfWiPEG1drgQ994Vr.gif",
    "tags": [
      "fail",
      "oops",
      "faceplant"
    ]
  },
  {
    "file": "fail-3BWJO4cqGYVbaQH3UU.gif",
    "tags": [
      "fail",
      "oops",
      "faceplant"
    ]
  },
  {
    "file": "fail-HNEmXQz7A0lDq.gif",
    "tags": [
      "fail",
      "oops",
      "faceplant"
    ]
  },
  {
    "file": "fail-ep78UZy5FVbfN6mhCU.gif",
    "tags": [
      "fail",
      "oops",
      "faceplant"
    ]
  },
  {
    "file": "fire-3KVcFEmdDl9NYaFTtx.gif",
    "tags": [
      "fire",
      "lit",
      "flame",
      "hot"
    ]
  },
  {
    "file": "fire-Mpcr9EWbsnhaE.gif",
    "tags": [
      "fire",
      "lit",
      "flame",
      "hot"
    ]
  },
  {
    "file": "fire-T2vDaYr8yRhrpFe6WE.gif",
    "tags": [
      "fire",
      "lit",
      "flame",
      "hot"
    ]
  },
  {
    "file": "fire-AHxv7bvQSxCUScHCWZ.gif",
    "tags": [
      "fire",
      "lit",
      "flame",
      "hot"
    ]
  },
  {
    "file": "fire-4C5hSpwdwke5024tvF.gif",
    "tags": [
      "fire",
      "lit",
      "flame",
      "hot"
    ]
  },
  {
    "file": "cool-62PP2yEIAZF6g.gif",
    "tags": [
      "cool",
      "chill",
      "smooth"
    ]
  },
  {
    "file": "cool-4shcuA9njrv9kE1iay.gif",
    "tags": [
      "cool",
      "chill",
      "smooth"
    ]
  },
  {
    "file": "cool-qUB8aayj9DNQI.gif",
    "tags": [
      "cool",
      "chill",
      "smooth"
    ]
  },
  {
    "file": "cool-fGCa0O9sogzEOTbBaP.gif",
    "tags": [
      "cool",
      "chill",
      "smooth"
    ]
  },
  {
    "file": "cool-JUqiFbumTAPYIeM8yJ.gif",
    "tags": [
      "cool",
      "chill",
      "smooth"
    ]
  },
  {
    "file": "hungry-UTkm6euG3wabBiUeQu.gif",
    "tags": [
      "hungry",
      "food",
      "eating",
      "snack"
    ]
  },
  {
    "file": "hungry-jKaFXbKyZFja0.gif",
    "tags": [
      "hungry",
      "food",
      "eating",
      "snack"
    ]
  },
  {
    "file": "hungry-12uXi1GXBibALC.gif",
    "tags": [
      "hungry",
      "food",
      "eating",
      "snack"
    ]
  },
  {
    "file": "hungry-qtAy4ycRtxfeU.gif",
    "tags": [
      "hungry",
      "food",
      "eating",
      "snack"
    ]
  },
  {
    "file": "hungry-l3mZ1tEwRVDguq02Q.gif",
    "tags": [
      "hungry",
      "food",
      "eating",
      "snack"
    ]
  },
  {
    "file": "coffee-RhS4D0U2qfNvyhwokA.gif",
    "tags": [
      "coffee",
      "morning",
      "caffeine",
      "wake up"
    ]
  },
  {
    "file": "coffee-jniEfGmj9ckgpTDebb.gif",
    "tags": [
      "coffee",
      "morning",
      "caffeine",
      "wake up"
    ]
  },
  {
    "file": "coffee-mRJz62ls3ogPP5KxFN.gif",
    "tags": [
      "coffee",
      "morning",
      "caffeine",
      "wake up"
    ]
  },
  {
    "file": "coffee-zBhZN8Cgtat9oHnN5A.gif",
    "tags": [
      "coffee",
      "morning",
      "caffeine",
      "wake up"
    ]
  },
  {
    "file": "hug-TKN7YK2i70gFy.gif",
    "tags": [
      "hug",
      "hugs",
      "cuddle"
    ]
  },
  {
    "file": "hug-4CTlTWDNqcBva.gif",
    "tags": [
      "hug",
      "hugs",
      "cuddle"
    ]
  },
  {
    "file": "hug-gl8ymnpv4Sqha.gif",
    "tags": [
      "hug",
      "hugs",
      "cuddle"
    ]
  },
  {
    "file": "hug-Yle9Yz9izeVRyiwavn.gif",
    "tags": [
      "hug",
      "hugs",
      "cuddle"
    ]
  },
  {
    "file": "hug-42YlR8u9gV5Cw.gif",
    "tags": [
      "hug",
      "hugs",
      "cuddle"
    ]
  },
  {
    "file": "pat-9Q249Qsl5cfLi.gif",
    "tags": [
      "pat",
      "pat on head",
      "there there"
    ]
  },
  {
    "file": "pat-Y1enhVugNKUN5cpSH1.gif",
    "tags": [
      "pat",
      "pat on head",
      "there there"
    ]
  },
  {
    "file": "pat-EbRPam1A4jEWkUokL8.gif",
    "tags": [
      "pat",
      "pat on head",
      "there there"
    ]
  },
  {
    "file": "pat-d9PRRv1yF0ZFTm3tVk.gif",
    "tags": [
      "pat",
      "pat on head",
      "there there"
    ]
  },
  {
    "file": "pat-2pOgZmF5b7mH2vVc0l.gif",
    "tags": [
      "pat",
      "pat on head",
      "there there"
    ]
  },
  {
    "file": "eye-roll-3oFzm25c9cyPt1TYDC.gif",
    "tags": [
      "eye roll",
      "eyeroll",
      "rolling eyes"
    ]
  },
  {
    "file": "eye-roll-qmfpjpAT2fJRK.gif",
    "tags": [
      "eye roll",
      "eyeroll",
      "rolling eyes"
    ]
  },
  {
    "file": "eye-roll-ycllbrN3Kx27e.gif",
    "tags": [
      "eye roll",
      "eyeroll",
      "rolling eyes"
    ]
  },
  {
    "file": "eye-roll-B4ORVnBvJCVvq.gif",
    "tags": [
      "eye roll",
      "eyeroll",
      "rolling eyes"
    ]
  },
  {
    "file": "eye-roll-dEdmW17JnZhiU.gif",
    "tags": [
      "eye roll",
      "eyeroll",
      "rolling eyes"
    ]
  },
  {
    "file": "high-five-QN6NnhbgfOpoI.gif",
    "tags": [
      "high five",
      "highfive"
    ]
  },
  {
    "file": "high-five-100QWMdxQJzQC4.gif",
    "tags": [
      "high five",
      "highfive"
    ]
  },
  {
    "file": "high-five-ag3PWAeHrCdWV0tlkD.gif",
    "tags": [
      "high five",
      "highfive"
    ]
  },
  {
    "file": "high-five-r2BtghAUTmpP2.gif",
    "tags": [
      "high five",
      "highfive"
    ]
  },
  {
    "file": "high-five-wrzf9P70YWLJK.gif",
    "tags": [
      "high five",
      "highfive"
    ]
  }
]

export const GIF_COUNT = 195
