/**
 * Quasar version — single source of truth.
 * Surfaced in the UI (header badge, footer, download card), the error pages,
 * the `x-quasar-version` response header on every proxied response, and the
 * generated self-host package (see scripts/make-release.sh).
 */

export const QUASAR_VERSION = "2.1.0";

/** One-line-per-release notes, newest first (kept short for UI display). */
export const RELEASE_NOTES: string[] = [
  "v2.1.0 — multi-account containers: cookie jars, storage namespaces and egress ride per tab, so two accounts on the same site (or Google+Discord, or true incognito tabs with auto-wiped jars) now coexist; upstream egress chaining via QUASAR_UPSTREAM_PROXY (residential-proxy CONNECT tunnel — the documented cheap fix for IP-reputation walls) with per-tab direct/upstream overrides and UA presets; server-side static cache (ETag/Last-Modified revalidating LRU for images/fonts/CSS/JS/wasm, QUASAR_HTTP_CACHE_MB) + AST-rewrite cache persisted to disk — repeat visits skip upstream fetches AND rewrites entirely; find-in-page (Ctrl+F) with match counts, tab drag-reorder / pin / mute / reopen-closed, per-tab egress+UA pickers; debug panel (live request ring with cache disposition, containers, egress, site-fix id); site-fix packs loaded from site-fixes.d/*.json with 30s hot-reload for community contributions; Dockerfile + fly.io/railway/render deploy templates; optional ffmpeg remux-to-HLS endpoint (QUASAR_REMUX=1) and an optional Playwright-based poToken farm attacking the BotGuard ceiling with a real browser",
  "v2.0.4 — virtual location layer (opt-in AST pass renames location/window.location reads to a shim reporting the real target origin — Discord's webpack runtime now boots; virtLoc flag, discord.com first); per-origin storage partitioning (localStorage/sessionStorage namespaced by the real target origin — no more cross-site boot-state corruption); YouTube levers: /youtubei/* requests get a server-side BotGuard poToken (bgutils-js, graceful tokenless fallback — BotGuard rejects synthetic server environments, the known hard ceiling) and a configurable browser-direct media passthrough (QUASAR_DIRECT_MEDIA_HOSTS, e.g. googlevideo.com for real Chrome TLS + real IP; off by default because googlevideo's SABR responses withhold CORS headers); Discord gateway dials with faithful Origin/User-Agent headers (ws bridge) + postMessage origin unwrap for OAuth popups; performance: undici HTTP/2 pooled dispatcher (QUASAR_NO_H2=1 reverts) and an ETag-keyed AST-rewrite cache that skips re-running acorn on repeat chunk loads",
  "v1.3.8 — built-in adblocker: network layer answers known ad & tracker URLs with empty 204s before any upstream connection, DOM layer sweeps ad elements (adsbygoogle slots, taboola/outbrain widgets, anti-adblock scripts) and hides ad containers; popup & popunder blocker (window.open hardened, target=_blank popunders in-tunneled or counted) with a live blocked counter in the browser chrome; upstream fetches moved to raw undici so Next's fetch instrumentation can no longer corrupt large streamed pages; stealth layer: Function.prototype.toString spoofing so every patched API (fetch, XHR, WebSocket, Worker, history, setAttribute, cookie, blob URLs…) reports [native code] with native name/length descriptors, navigator.webdriver=false, and light canvas/WebGL/audio fingerprint farbling (per-page stable, cross-read consistent; QUASAR_NO_STEALTH=1 to disable)",
  "v1.2.7 — streaming HTML rewriter (first paint while the body is still in flight), AST-based JS rewriting via acorn, full DOM trap layer (MutationObserver safety net, srcset setters, focus/notification fixes), per-site fix database, AES-256-GCM encrypted proxied URLs with per-deployment keys, SSRF guard + rate limiting + optional password gate, HLS (m3u8) rewriting, JSON media URLs, redirect-hop cookie fix (login flows), stream-safe timeouts, referer restoration, Worker hooks, tracking-param stripping, keyboard shortcuts (Alt+T/W/←/→), compact new-tab page",
  "v1.1 — self-host download package, WS transport auto-detection",
  "v1.0 — engine core: rewriter, hooks, service worker, WS bridge, tabbed UI",
];
