# syntax=docker/dockerfile:1
# ============================================================================
# Veil OS — full-stack production image
#
# One container, the whole desktop (identical topology to the dev sandbox):
#   :{$PORT}  Caddy gateway (public)  ──┐
#      ├─ /                    → :3000  Next.js 16 (standalone build)
#      └─ ?XTransformPort=N   → :N     mini-services (chat, ws, freetube, bridge)
#
# State (SQLite db, chat files, secrets) lives in ONE volume mounted at
# /home/z/my-project/db — the boot script symlinks upload/ → db/upload so a
# single disk covers everything (Render allows one disk per service).
#
# The workdir is intentionally /home/z/my-project: a handful of source files
# reference absolute paths under it (chat HMAC secret, quasar key default);
# keeping the layout identical means zero code changes for production.
# ============================================================================

# ---- Stage 1: build the Next.js standalone bundle --------------------------
FROM oven/bun:1 AS build
WORKDIR /home/z/my-project

# deps first (layer cache)
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# prisma client must be generated BEFORE next build (it gets traced into
# the standalone bundle)
COPY prisma ./prisma
RUN bunx prisma generate

# app source (.dockerignore keeps state/secrets/junk out)
COPY . .
RUN bun run build

# mini-service deps (chat-service carries socket.io; the others are
# bun-stdlib only but install anyway for lockfile fidelity)
RUN cd mini-services/chat-service && bun install --frozen-lockfile || true

# ---- Stage 2: runtime ------------------------------------------------------
FROM oven/bun:1 AS runtime
WORKDIR /home/z/my-project

ENV NODE_ENV=production \
    DATABASE_URL=file:/home/z/my-project/db/custom.db \
    QUASAR_KEY_FILE=/home/z/my-project/db/.quasar-key \
    HOSTNAME=0.0.0.0
    # OWNER_DEFAULT_PASSWORD is generated by deploy/start.sh on first boot.

# the gateway
COPY --from=caddy:2 /usr/bin/caddy /usr/bin/caddy

# Next standalone server — self-contained (traced node_modules + static +
# public are inside; the build script copies static/public into it)
COPY --from=build /home/z/my-project/.next/standalone ./.next/standalone

# Prisma CLI + full node_modules for the boot-time schema push
COPY --from=build /home/z/my-project/node_modules ./node_modules
COPY --from=build /home/z/my-project/prisma ./prisma
COPY package.json bun.lock ./

# mini-services (quasar-bridge imports ../../src/lib/veil/quasar/*)
COPY --from=build /home/z/my-project/mini-services ./mini-services
COPY src/lib/veil/quasar ./src/lib/veil/quasar

# boot script + gateway config
COPY deploy ./deploy

# state dirs (volume mounts overlay these)
RUN mkdir -p db upload/veil-chat-files \
 && chmod +x deploy/start.sh

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=90s --retries=3 \
  CMD bun -e 'fetch("http://127.0.0.1:"+(process.env.PORT||80)+"/").then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))'

CMD ["bash", "deploy/start.sh"]
