#!/usr/bin/env bun
/**
 * Veil — local GIF library builder (one-time / refresh tool).
 *
 * Downloads a curated set of reaction GIFs from Giphy's public API into
 * public/gifs/ and mirrors them to upload/veil-gifs/ (the revert-surviving
 * store, like upload/veil-artifacts). Generates the manifest consumed by
 * src/lib/veil/gif-library.ts.
 *
 * After running this script, paste the printed manifest block into
 * src/lib/veil/gif-library.ts (or let --write do it).
 *
 * Runtime search then never touches Giphy — GIFs are sourced like the
 * wallpapers: local files, served same-origin.
 */

const KEY = "GlVGYHkr3WSBnllca54iNt0yFbjz7L65"
const PER_TAG = 5
const ROOT = new URL("..", import.meta.url).pathname // project root
const OUT_PUBLIC = `${ROOT}public/gifs`
const OUT_UPLOAD = `${ROOT}upload/veil-gifs`

// tag -> extra search synonyms baked into the manifest
const TAGS = [
  ["happy", "glad", "smile", "yay"],
  ["excited", "hype", "energetic"],
  ["love", "heart", "adore"],
  ["sad", "unhappy", "depressing"],
  ["cry", "crying", "tears", "sob"],
  ["angry", "mad", "rage", "annoyed"],
  ["laugh", "laughing", "lol", "haha"],
  ["funny", "joke", "comedy"],
  ["wow", "amazed", "amazing"],
  ["shock", "shocked", "surprised", "gasp"],
  ["scared", "afraid", "fear", "scream"],
  ["thinking", "hmm", "think"],
  ["sleepy", "tired", "sleep", "zzz"],
  ["bored", "boring", "meh"],
  ["dance", "dancing", "moves"],
  ["party", "celebrate", "celebration", "confetti"],
  ["congrats", "congratulations", "well done"],
  ["thanks", "thank you", "thx"],
  ["sorry", "apology", "apologize"],
  ["bye", "goodbye", "farewell"],
  ["hi", "hello", "hey", "wave"],
  ["yes", "yeah", "agree"],
  ["no", "nope", "nah", "disagree"],
  ["shrug", "idk", "whatever", "meh"],
  ["facepalm", "smh", "doh"],
  ["thumbs up", "approve", "nice"],
  ["clap", "clapping", "applause", "bravo"],
  ["cat", "cats", "kitten", "kitty"],
  ["dog", "dogs", "puppy", "pup"],
  ["gaming", "game", "gamer", "videogame"],
  ["win", "winning", "victory", "success"],
  ["fail", "oops", "faceplant"],
  ["fire", "lit", "flame", "hot"],
  ["cool", "chill", "smooth"],
  ["hungry", "food", "eating", "snack"],
  ["coffee", "morning", "caffeine", "wake up"],
  ["hug", "hugs", "cuddle"],
  ["pat", "pat on head", "there there"],
  ["eye roll", "eyeroll", "rolling eyes"],
  ["high five", "highfive"],
]

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

async function jget(url) {
  const res = await fetch(url, {
    headers: { accept: "application/json", "user-agent": UA },
    signal: AbortSignal.timeout(15_000),
  })
  if (!res.ok) throw new Error(`${res.status} for ${url}`)
  return res.json()
}

async function download(url, dest) {
  const res = await fetch(url, {
    headers: { "user-agent": UA },
    signal: AbortSignal.timeout(30_000),
  })
  if (!res.ok) throw new Error(`${res.status} for ${url}`)
  const buf = Buffer.from(await res.arrayBuffer())
  const { writeFileSync } = await import("node:fs")
  writeFileSync(dest, buf)
  return buf.byteLength
}

const { mkdirSync, existsSync, readdirSync, writeFileSync } = await import("node:fs")

mkdirSync(OUT_PUBLIC, { recursive: true })
mkdirSync(OUT_UPLOAD, { recursive: true })

const seenIds = new Set()
const manifest = []
let total = 0

for (const [tag, ...synonyms] of TAGS) {
  let data
  try {
    data = await jget(
      `https://api.giphy.com/v1/gifs/search?api_key=${KEY}&q=${encodeURIComponent(
        tag + " reaction"
      )}&limit=${PER_TAG}&rating=pg`
    )
  } catch (e) {
    console.error(`! tag "${tag}" failed: ${e.message}`)
    continue
  }
  let n = 0
  for (const g of data.data || []) {
    if (!g.id || seenIds.has(g.id)) continue
    const fw = g.images?.fixed_width?.url
    if (!fw) continue
    const file = `${tag.replace(/\s+/g, "-")}-${g.id}.gif`
    const destPublic = `${OUT_PUBLIC}/${file}`
    try {
      const size = await download(fw, destPublic)
      if (size > 2_500_000) {
        console.error(`! skipped huge ${file} (${size})`)
        continue
      }
      seenIds.add(g.id)
      manifest.push({ file, tags: [tag, ...synonyms] })
      total += size
      n++
    } catch (e) {
      console.error(`! download failed ${file}: ${e.message}`)
    }
  }
  console.log(`+ ${tag}: ${n}`)
}

// Mirror to upload/veil-gifs (durable, revert-surviving)
for (const f of readdirSync(OUT_PUBLIC)) {
  if (!f.endsWith(".gif")) continue
  const { copyFileSync } = await import("node:fs")
  copyFileSync(`${OUT_PUBLIC}/${f}`, `${OUT_UPLOAD}/${f}`)
}

const manifestTs = `// AUTO-GENERATED by scripts/fetch-gifs.mjs — local GIF library
// (files in public/gifs/, mirrored to upload/veil-gifs/). Do not hand-edit;
// re-run the script to refresh.

export type GifEntry = { file: string; tags: string[] }

export const GIF_LIBRARY: GifEntry[] = ${JSON.stringify(manifest, null, 2)}

export const GIF_COUNT = ${manifest.length}
`

writeFileSync(`${ROOT}scripts/gif-manifest.generated.ts`, manifestTs)
console.log(`\nDone: ${manifest.length} GIFs, ${(total / 1e6).toFixed(1)} MB`)
console.log(`Manifest written to scripts/gif-manifest.generated.ts`)
console.log(`(gif-search route reads public/gifs directly — see api/gif-search/route.ts)`)
